run:
  deadline: 8m

  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # from this option's value (see skip-dirs-use-default).
  #skip-dirs:

  # funcs.go and template.go are skipped because they weren't changed,
  # and still cause issues.  I suspect that the upstream code was never
  # linted.  Additionally, the exec_test.go and multi_test.go are
  # excluded as those issues stem from existing upstream lint issues.
  skip-files:
    - internal/pkg/text/template/exec_test.go
    - internal/pkg/text/template/multi_test.go
    - internal/pkg/text/template/funcs.go
    - internal/pkg/text/template/template.go

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  #skip-dirs-use-default: true
  linters:
    enable:
      - lll
      - vet
      - gofmt
      - golint
      - structcheck
      - unconvert
      - deadcode
      - goconst
      - unused
      - gosimple
      - varcheck
      - misspell
      - gocyclo
      - vetshadow
      - megacheck
      - stylecheck
      - govet
    disable:
      - typecheck
      - ineffassign
      - errcheck
      - interfacer
      - unparam
      - nakedret
      - prealloc
      - scopelint
      - gocritic
  issues:
    exclude-use-default: true
  output:
    # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
    format: colored-line-number

    # print lines of code with issue, default is true
    print-issued-lines: true

    # print linter name in the end of issue text, default is true
    print-linter-name: true

    # make issues output unique by line, default is true
    uniq-by-line: true